### ISSUE TITLE
Wikidata evaluation seems to be buggy!

### ISSUE THREAD

**Issue by vinaysetty** [smart-task/smart-dataset#10]
It seems like Wikidata ground truth type (a list) converted to a string and if the predicted type is contained in this string then it is considered a match. This results in false positives i.e, if predicted type is "location" and ground truth type is "geographic location" it will be a match. 

```
   for j in range(len(lst_pred)):
            if (lst_pred[j]) in str(lst_correct):
                           #print(lst_pred[j] + ' is present in correct list')
                           rank = lst_correct.index(lst_pred[j]) + 1
                           break
```
https://github.com/smart-task/smart-dataset/blob/eeb7d124f9a631b91d5bc81a55ba30dc5f11b12c/evaluation/wikidata/code_files/evaluate_lcquad2.py#L28

While that should give an advantage to the submitted system, what actually happens is in [line 30](https://github.com/smart-task/smart-dataset/blob/eeb7d124f9a631b91d5bc81a55ba30dc5f11b12c/evaluation/wikidata/code_files/evaluate_lcquad2.py#L30) when the index is looked up it results in an exception. And the exception is caught outside the for loop which means rest of the candidate types are ignored and rank value is set to be 0. Any correct answers down the list are ignored!

**This might invalidate the results published by the organizers!**

Ideally the type list should be converted to a set and checked or it should be done in 2 for loops. It will be inefficient but correct.

Another issue is the index of the type in the ground truth list is used? `rank = lst_correct.index(lst_pred[j]) + 1` my understanding is that the rank in reciprocal rank is the rank of the correct answer in the predicted list not in the ground truth list.

**Comment by nandana** [comment]
@mohnish-rygbee @uttam1216 can you please check this issue?

**Comment by uttam1216** [comment]
Dear Vinay,

Thanks for raising the issue. Actually, due to some communication gap the actual script used for evaluation last year was not uploaded here in this repo and thus the script you are referring is old. The script which was used for evaluation has code as can be seen in the screenshot below: 

![Screenshot from 2022-05-24 15-00-41](https://user-images.githubusercontent.com/49790375/170042199-9088050b-6c26-44a5-84d9-2ebbe949722a.jpg)

We will upload this jupyter notebook used last year for evaluation. Sorry for inconvinience.

Best Regards,
Uttam Kumar

**Comment by vinaysetty** [comment]
@uttam1216 thank you for clarifying it. I am still baffled by the buggy code which was public and we were using it for over a year for evaluation. This reduces the trust in the numbers reported by the organizers and explains why we couldn't reproduce the numbers reported by organizers. 

This still doesn't seem to address my second part of the issue. I.e, for MRR the index of the predicted list should be used as the rank. Not from the ground truth `lst_correct`. Can you clarify this?
